name: Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: actions/checkout@v3
      - run: echo "${{ secrets.ENV }}" > .env
      - run: npm install
      - run: npm run build
      - run: npm run migration:run
      - run: docker rmi -f test-backend:latest
      - run: docker build -t test-backend:latest .
      - run: docker rm -f test-backend
      - run: docker run -d --name test-backend  --network host -p 3000:3000 test-backend:latest


